# Generated by Django 5.1.6 on 2025-03-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetsAdoption", "0001_initial"),
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="pet_lever",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="Users.petlever",
            ),
        ),
    ]
